### ISSUE TITLE
Image shows Ada embedding vectors outside of -1 to 1 range

### ISSUE THREAD

**Issue by mwiemer-microsoft** [Azure-Samples/miyagi#141]
[assets/images/sk-memory-orchestration.png](https://github.com/Azure-Samples/miyagi/blob/main/assets/images/sk-memory-orchestration.png) shows a question vector with a value of -1.53, but ada-002 is "normalized to length 1" per [OpenAI docs](https://platform.openai.com/docs/guides/embeddings/limitations-risks#:~:text=OpenAI%20embeddings%20are%20normalized%20to%20length%201). Updating the image should reduce confusion for new AI coders :)

![image](https://github.com/Azure-Samples/miyagi/assets/80539004/c12cfa59-2330-400b-9b3a-c508df00b909)

Resolved with my super awesome paint skills:

![image](https://github.com/Azure-Samples/miyagi/assets/80539004/7ea97b82-6751-4cae-8fac-570752d4a009)

**Comment by mwiemer-microsoft** [comment]
Oops, I'm dumb! Vector length is normalized, but individual elements of the vector may have an absolute value greater than 1. Closing this.

**Comment by thegovind** [comment]
no worries at all. Glad you resolved it, and thanks for posting. It's more of an illustration of how text is represented in models to drive clarity.
