### ISSUE TITLE
Yarn install fails with an error "husky - .git can't be found"

### ISSUE THREAD

**Issue by cyberkoolman** [Azure-Samples/miyagi#143]
I wanted to validate running it locally, At ui/typescript, "yarn install" fails with the error "husky - .git can't be found".  What do I need to do?  Also, would appreciate if docs clearly state how to run locally with step-by-step instructions.

**Comment by thegovind** [comment]
Thanks for the feedback @cyberkoolman. This bug was introduced when I was cleaning up the folders to simplify. I appreciate the note on local instructions as well. Will prioritize that right after my vacation.
