### ISSUE TITLE
Provide clearer documentation on how to run local

### ISSUE THREAD

**Issue by karstenjMSFT** [Azure-Samples/miyagi#177]
Can this project be run locally? If so, can documentation be provided as such on how to get it up and running?

**Comment by thegovind** [comment]
Thank you, @karstenjMSFT. I'm working on a 1-click deploy at https://github.com/Azure-Samples/miyagi/tree/main/deploy#deploying-the-solution-in-your-azure-subscription If you have some cycles, would appreciate community PRs. I'm just swamped.
